# Business services module

from app.services.ai_service import (
    AIService,
    AIServiceError,
    AIRateLimitError,
    AIUsageLimitError,
    AIProviderError,
    GenerationResult,
    ai_service,
)
from app.services.ai_usage_service import (
    UsageStatus,
    get_usage_status,
    check_usage_limit,
    record_generation,
    record_generation_error,
    get_usage_history,
    get_usage_stats,
)
from app.services.ad_copy_service import (
    HeadlineGenerationResponse,
    DescriptionGenerationResponse,
    CTAGenerationResponse,
    FullAdCopyGenerationResponse,
    generate_headlines,
    generate_descriptions,
    generate_ctas,
    generate_full_ad_copy,
    PLATFORM_LIMITS,
)
from app.services.cache_service import (
    init_redis,
    close_redis,
    get_redis,
    cache_get,
    cache_set,
    cache_delete,
    cache_delete_pattern,
    cached,
    CacheKey,
    CacheTTL,
    invalidate_user_cache,
    invalidate_org_cache,
    invalidate_campaign_cache,
    invalidate_subscription_cache,
)

__all__ = [
    # AI Service
    "AIService",
    "AIServiceError",
    "AIRateLimitError",
    "AIUsageLimitError",
    "AIProviderError",
    "GenerationResult",
    "ai_service",
    # AI Usage Service
    "UsageStatus",
    "get_usage_status",
    "check_usage_limit",
    "record_generation",
    "record_generation_error",
    "get_usage_history",
    "get_usage_stats",
    # Ad Copy Service
    "HeadlineGenerationResponse",
    "DescriptionGenerationResponse",
    "CTAGenerationResponse",
    "FullAdCopyGenerationResponse",
    "generate_headlines",
    "generate_descriptions",
    "generate_ctas",
    "generate_full_ad_copy",
    "PLATFORM_LIMITS",
    # Cache Service
    "init_redis",
    "close_redis",
    "get_redis",
    "cache_get",
    "cache_set",
    "cache_delete",
    "cache_delete_pattern",
    "cached",
    "CacheKey",
    "CacheTTL",
    "invalidate_user_cache",
    "invalidate_org_cache",
    "invalidate_campaign_cache",
    "invalidate_subscription_cache",
]
